# Generated by Django 5.2.5 on 2025-08-30 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Police_station_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='users_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='technical_issue_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=1000)),
                ('reply', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users_table')),
            ],
        ),
        migrations.CreateModel(
            name='familiar_person_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('POLICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users_table')),
            ],
        ),
        migrations.CreateModel(
            name='camera_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users_table')),
            ],
        ),
        migrations.CreateModel(
            name='visitor_log_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('FAMILIAR_PERSON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.familiar_person_table')),
            ],
        ),
        migrations.CreateModel(
            name='reports_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=100)),
                ('STATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station_table')),
                ('VISITORS_LOG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.visitor_log_table')),
            ],
        ),
    ]
