# Generated by Django 5.2.5 on 2025-08-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports_table',
            name='response',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
