# Generated by Django 5.2.5 on 2025-11-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reports_table_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('CAMERA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera_table')),
            ],
        ),
    ]
