# Generated by Django 5.2.5 on 2025-11-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_table',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
