# Generated by Django 5.2.5 on 2025-11-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_notification_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_table',
            name='VISITORS_LOG',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.notification_table'),
        ),
    ]
